package com.example.di_1_hexentanz.gameboard;

public enum GameState {
    MY_TURN, ROLL_DICE, SELECT_WITCH_MOVE, CONFIRM_WITCH_MOVE, NOT_MY_TURN, PUT_WITCH_ON_BOARD, SELECT_WITCH_COLOR, CONFIRM_WITCH_COLOR
}
